# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Added this task=Command line-
#means displays all folder structure in ubunto agent machine
- task: CmdLine@2
  inputs:
    script: |
      echo "Listing files..."
      ls -R
#task=copy file
#in Content->changed from '**/.war' to '**/target/*.war'
- task: CopyFiles@2
  inputs:
    Contents: '**/target/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
#task=PublishBuildArtifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warFile'
    publishLocation: 'Container'
